#!/bin/sh

FREEZE=${FREEZE:-../freeze}
MELT=${MELT:-../melt}

for i in [0-9][0-9][0-9]; do
    cp $i x$i
    if "$FREEZE" x$i 2>/dev/null; then
        if cmp $i.ice x$i.ice 1>/dev/null 2>/dev/null; then
	    if "$MELT" x$i.ice 2>/dev/null; then
		if cmp x$i $i; then
		    echo $i: ok
		else
		    echo $i: melt failed to produce an identical file
		fi
	    else
		echo $i: melt returned an error status
	    fi
        else
	    echo $i: freeze failed to produce an identical file
        fi
    else
	echo $i: freeze returned an error status
    fi
    rm -f x$i x$i.ice
done
